services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}); do
        echo 'Esperando a MinIO...'; sleep 1;
      done;
      /usr/bin/mc mb -p local/${S3_BUCKET} || true;      
      echo 'Bucket listo';
      exit 0;
      "

  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M
      --node-id 0 --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:9094
    ports:
      - "9092:9092"
      - "9094:9094"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8085:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda

volumes:
  postgres_data:
    driver: local
  minio_data:
  redpanda_data: